In [2]:
import numpy as np
import scipy.linalg as slin

In [3]:
A = np.asarray([[2,1,2],
               [1,-2,1],
               [1,2,3],
               [1,1,1]])

b =np.asarray([[6],
              [1],
              [5],
              [2]])

In [4]:
ATA = np.transpose(A) @ A
ATb = np.transpose(A) @ b

In [5]:
L = np.linalg.cholesky(ATA)

In [6]:
y = slin.solve_triangular(L,ATb,lower=True)

In [7]:
x = slin.solve_triangular(np.transpose(L),y,lower=False)

In [8]:
x

array([[1.7],
       [0.6],
       [0.7]])

In [9]:
A @ x

array([[5.4],
       [1.2],
       [5. ],
       [3. ]])

In [10]:
L

array([[2.64575131, 0.        , 0.        ],
       [1.13389342, 2.9519969 , 0.        ],
       [3.40168026, 1.06465462, 1.51495279]])

In [11]:
Q,R = np.linalg.qr(A)


In [12]:
Q

array([[-0.75592895,  0.04839339,  0.41120147],
       [-0.37796447, -0.82268766, -0.38955929],
       [-0.37796447,  0.53232731, -0.7574764 ],
       [-0.37796447,  0.19357357,  0.32463274]])

In [13]:
R

array([[-2.64575131, -1.13389342, -3.40168026],
       [ 0.        ,  2.9519969 ,  1.06465462],
       [ 0.        ,  0.        , -1.51495279]])

In [14]:
x = np.linalg.inv(R) @ np.transpose(Q) @ b

In [15]:
x

array([[1.7],
       [0.6],
       [0.7]])

In [16]:
U, Sigma ,VT = np.linalg.svd(A)
Sigma_mat = np.zeros(A.shape)
Sigma_mat[:3,:3] = np.diag(Sigma)

In [17]:
print(U)
print(Sigma_mat)
print(VT)




[[-5.84030814e-01  1.99650590e-01 -6.01585233e-01 -5.07092553e-01]
 [-6.24673545e-02  9.55110190e-01  2.35140225e-01  1.69030851e-01]
 [-7.35399565e-01 -2.06954617e-01  6.45257519e-01  6.93889390e-17]
 [-3.37925018e-01 -7.12316840e-02 -4.07979185e-01  8.45154255e-01]]
[[4.96978399 0.         0.        ]
 [0.         2.53339065 0.        ]
 [0.         0.         0.93977598]
 [0.         0.         0.        ]]
[[-0.46357217 -0.45632169 -0.75952047]
 [ 0.42481607 -0.8667083   0.26143455]
 [-0.77758096 -0.20146273  0.59563464]]


In [18]:
Sigma_mat_pinv = np.transpose(np.zeros(A.shape))
Sigma_mat_pinv[:3,:3] = np.diag(1/Sigma[:3])
Sigma_mat_pinv.round(3)

array([[0.201, 0.   , 0.   , 0.   ],
       [0.   , 0.395, 0.   , 0.   ],
       [0.   , 0.   , 1.064, 0.   ]])

In [19]:
y = Sigma_mat_pinv @ U.T @ b


In [20]:
x = VT.T @ y

In [21]:
x

array([[1.7],
       [0.6],
       [0.7]])

In [22]:
r = A @ x - b
print(r)

[[-6.00000000e-01]
 [ 2.00000000e-01]
 [ 3.55271368e-15]
 [ 1.00000000e+00]]


In [23]:
ATr = A.T @ r
print(ATr)

[[4.66293670e-15]
 [6.66133815e-15]
 [1.17683641e-14]]


In [39]:
W = np.diag(np.asarray([1000,1,1,1]))
print(W)

[[1000    0    0    0]
 [   0    1    0    0]
 [   0    0    1    0]
 [   0    0    0    1]]


In [40]:
x = np.linalg.inv((A.T @ W @ A)) @ A.T @ W @ b
print(x)

[[2.17244031]
 [0.69218347]
 [0.48106425]]


In [41]:
r = A @ x - b
print (r)

[[-8.07412819e-04]
 [ 2.69137606e-01]
 [-8.34887715e-13]
 [ 1.34568803e+00]]
