In [37]:
import numpy as np

In [38]:
def gramSchmidt(A):
    n=A.shape[1]
    R = np.zeros((n,n))
    Q = np.zeros(A.shape)
    R[0,0] = np.linalg.norm(A[:,0])
    Q[:,0] = A[:,0]/R[0,0]
    for i in range(1,n):
        Q[:,i] = A[:,i]
        for j in range(0,i):
            R[j,i] = Q[:,j].T @ A[:,i] 
            Q[:,i] = Q[:,i] - R[j,i] * Q[:,j]
        R[i,i] = np.linalg.norm(Q[:,i])
        Q[:,i] = Q[:,i]/R[i,i]
    return Q,R            

In [39]:
ep = 1.1e-10
A = np.asarray([[1,1,1],
               [ep,0,0],
               [0,ep,0],
               [0,0,ep]])


In [40]:
print(A)

[[1.0e+00 1.0e+00 1.0e+00]
 [1.1e-10 0.0e+00 0.0e+00]
 [0.0e+00 1.1e-10 0.0e+00]
 [0.0e+00 0.0e+00 1.1e-10]]


In [41]:
Q1,R1 = gramSchmidt(A)
print(Q1)
print('==============================')
print(R1)


[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.10000000e-10 -7.07106781e-01 -7.07106781e-01]
 [ 0.00000000e+00  7.07106781e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.07106781e-01]]
[[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.55563492e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.55563492e-10]]


In [42]:
def modGramSchmidt(A):
    n=A.shape[1]
    R = np.zeros((n,n))
    Q = np.zeros(A.shape)
    R[0,0] = np.linalg.norm(A[:,0])
    Q[:,0] = A[:,0]/R[0,0]
    for i in range(1,n):
        Q[:,i] = A[:,i]
        for j in range(0,i):
            R[j,i] = Q[:,j].T @ Q[:,i] 
            Q[:,i] = Q[:,i] - R[j,i] * Q[:,j]
        R[i,i] = np.linalg.norm(Q[:,i])
        Q[:,i] = Q[:,i]/R[i,i]
    return Q,R    

In [43]:
Q2,R2 = modGramSchmidt(A)
print(Q2)
print('==============================')
print(R2)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.10000000e-10 -7.07106781e-01 -4.08248290e-01]
 [ 0.00000000e+00  7.07106781e-01 -4.08248290e-01]
 [ 0.00000000e+00  0.00000000e+00  8.16496581e-01]]
[[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.55563492e-10 7.77817459e-11]
 [0.00000000e+00 0.00000000e+00 1.34721936e-10]]


In [44]:
print(np.linalg.norm(Q1.T @ Q1 - np.identity(Q1.shape[1]),'fro'))

0.7071067811865477


In [45]:
print(np.linalg.norm(Q2.T @ Q2 - np.identity(Q2.shape[1]),'fro'))

1.270170592219576e-10
