In [1]:
import numpy as np

In [3]:
A = np.asarray([[1,2,3,4],
              [2,4,-4,8],
              [-5,4,1,5],
              [5,0,-3,-7]])

In [4]:
A

array([[ 1,  2,  3,  4],
       [ 2,  4, -4,  8],
       [-5,  4,  1,  5],
       [ 5,  0, -3, -7]])

In [5]:
ATA = np.transpose(A) @ A
ATA

array([[ 55, -10, -25, -40],
       [-10,  36,  -6,  60],
       [-25,  -6,  35,   6],
       [-40,  60,   6, 154]])

In [15]:
(value, vector) = np.linalg.eig(ATA)
indexOfMaxValue = np.argmax(value)

print(np.sqrt(value[indexOfMaxValue]))
print(np.linalg.norm(A,2))

13.858100376465329
13.858100376465329


In [12]:
vector[:,indexOfMaxValue]

array([-0.29618621,  0.35616716,  0.06730298,  0.88367923])